name: Run Pre-Commit

on:
  pull_request: {}
  push:
    paths-ignore:
      - 'examples/**'
    branches:
      - dev
      - main

jobs:
  pre-commit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set file mode to false
        run: |
          git config core.filemode false
      - uses: pre-commit/action@v2.0.3
